name: Build and Release yt-dlp GUI

on:
  schedule:
    # Run every Monday at 6:00 UTC
    - cron: '0 6 * * 1'
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - testing  # Add your testing branch

permissions:
  contents: write

jobs:
  check-updates:
    runs-on: ubuntu-latest
    outputs:
      has_updates: ${{ steps.check_updates.outputs.has_updates }}
      yt_dlp_version: ${{ steps.get_versions.outputs.yt_dlp_version }}
      ffmpeg_version: ${{ steps.get_versions.outputs.ffmpeg_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyQt5 PyInstaller requests
      
      - name: Run fetch_binaries.py
        run: python yt_dlp_gui/fetch_binaries.py
      
      - name: Get current versions
        id: get_versions
        run: |
          python yt_dlp_gui/get_current_versions.py >> $GITHUB_OUTPUT
      
      - name: Check for updates
        id: check_updates
        run: |
          # Create a versions file if it doesn't exist
          if [ ! -f versions.json ]; then
            echo '{"yt-dlp": "unknown", "ffmpeg": "unknown"}' > versions.json
          fi
          
          # Read current versions
          current_versions=$(cat versions.json)
          
          # Get new versions from the previous step
          yt_dlp_version="${{ steps.get_versions.outputs.yt_dlp_version }}"
          ffmpeg_version="${{ steps.get_versions.outputs.ffmpeg_version }}"
          
          # Check if versions have changed
          if [ "$current_versions" != "{\"yt-dlp\": \"$yt_dlp_version\", \"ffmpeg\": \"$ffmpeg_version\"}" ]; then
            echo "Updates found. Updating versions file."
            
            # Update the versions file
            echo "{\"yt-dlp\": \"$yt_dlp_version\", \"ffmpeg\": \"$ffmpeg_version\"}" > versions.json
            
            # Commit the updated versions file
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add versions.json
            git commit -m "Update version information [skip ci]"
            git push
            
            echo "has_updates=true" >> $GITHUB_OUTPUT
          else
            echo "No updates found."
            echo "has_updates=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check-updates
    if: needs.check-updates.outputs.has_updates == 'true'
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        # Add a timeout for each job to prevent cancellation
        timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyQt5 PyInstaller requests
      
      - name: Run fetch_binaries.py
        run: python yt_dlp_gui/fetch_binaries.py
      
      - name: Build application
        run: python build.py
      
      - name: Verify executable exists
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            EXECUTABLE="dist/yt-dlp GUI.exe"
          else
            EXECUTABLE="dist/yt-dlp GUI"
          fi
          
          if [ -f "$EXECUTABLE" ]; then
            echo "Executable found."
          else
            echo "Executable not found."
            exit 1
          fi
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: yt-dlp-gui-${{ matrix.os }}
          path: |
            dist/yt-dlp GUI.exe
            dist/yt-dlp GUI
          retention-days: 30  # Optional: Set artifact retention period

  release:
    needs: [check-updates, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download artifacts
        uses: actions/download-artifact@v4  # Updated to v4
        with:
          path: artifacts
      
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.check-updates.outputs.yt_dlp_version }}.${{ needs.check-updates.outputs.ffmpeg_version }}.${{ steps.date.outputs.date }}
          name: Release ${{ needs.check-updates.outputs.yt_dlp_version }}.${{ needs.check-updates.outputs.ffmpeg_version }}.${{ steps.date.outputs.date }}
          body: |
            Automated release of yt-dlp GUI with updated binaries.
            
            yt-dlp version: ${{ needs.check_updatess.outputs.yt_dlp_version }}
            FFmpeg version: ${{ needs.check_updates.outputs.ffmpeg_version }}
            
            This release includes the latest versions of yt-dlp and ffmpeg.
          files: |
            artifacts/yt-dlp-gui-windows-latest/yt-dlp GUI.exe
            artifacts/yt-dlp-gui-macos-latest/yt-dlp GUI
            artifacts/yt-dlp-gui-ubuntu-latest/yt-dlp GUI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}